services:
  postgres:
    image: postgres:15
    container_name: my-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - infrastructure_default

  service-courier:
    build: .
    command: ["/service"]
    ports:
      - "8082:8080"
    env_file: .env
    environment:
      - PORT=${PORT}
      - POSTGRES_HOST=my-postgres
      - TZ=Europe/Moscow
    networks:
      - infrastructure_default

  service-courier-worker:
    build: .
    command: ["/worker"]
    env_file: .env
    environment:
      - POSTGRES_HOST=my-postgres
      - TZ=Europe/Moscow
      - KAFKA_BROKERS=${KAFKA_BROKERS}
    networks:
      - infrastructure_default

volumes:
  pgdata:
  
networks:
  infrastructure_default:
    external: true