global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "go-app"
    static_configs:
      - targets: ["service-courier:8080"]

  - job_name: "courier-worker"
    metrics_path: /metrics
    static_configs:
      - targets: ["service-courier-worker:9101"]
